// Copyright (c) 2022 Jonathan Lang

//---------- -------------------------- -------
//---------- !!! AUTOGENERATED CONTENT !!! -------
//---------- -------------------------- -------

//Runtime Monitoring
//File generated: 2024-05-20 15:13:18Z
//Please dont change the contents of this file. Otherwise IL2CPP runtime may not work with runtime monitoring!
//Ensure that this file is located in Assembly-CSharp. Otherwise this file may not compile.
//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring

#if ENABLE_IL2CPP && !DISABLE_MONITORING

internal class IL2CPP_AOT_6XZWPJIOSH0037GXWGO2
{
    //Value Processor Method Definitions

    [UnityEngine.Scripting.PreserveAttribute]
    [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.NoOptimization)]
    private static void AOT()
    {
        //  [Field Definitions] 

        // Player.PlayerController::_isRaycastGrounded (System.Boolean)
        // Player.PlayerController::_isRaycastSliding (System.Boolean)
        // Player.PlayerController::_isSnappingToGround (System.Boolean)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<System.Object, System.Boolean>();

        // Player.PlayerController::_groundContactCount (System.Int32)
        // Player.PlayerController::_steepContactCount (System.Int32)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<System.Object, System.Int32>();

        // Baracuda.Monitoring.Modules.SystemMonitor::_operatingSystem (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_operatingSystemFamily (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_deviceType (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_deviceModel (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_deviceName (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_processorType (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_processorFrequency (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_processorCount (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_systemMemory (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsDeviceName (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsDeviceType (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsMemorySize (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsMultiThreaded (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_batteryLevel (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_batteryStatus (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_dataPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_persistentDataPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_consoleLogPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_streamingAssetsPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_temporaryCachePath (System.String)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<System.Object, System.Object>();

        // Baracuda.Monitoring.Modules.FPSMonitor::_fps (System.Single)
        // Player.PlayerController::_internalCoyoteTimer (System.Single)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<System.Object, System.Single>();

        // Player.PlayerController::_velocity (UnityEngine.Vector3)
        // Player.PlayerController::_desiredVelocity (UnityEngine.Vector3)
        // Player.PlayerController::_contactNormal (UnityEngine.Vector3)
        // Player.PlayerController::_steepNormal (UnityEngine.Vector3)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<System.Object, UnityEngine.Vector3>();

        //  [Property Definitions] 

        // Player.PlayerController::OnGround (System.Boolean)
        // Player.PlayerController::OnSteep (System.Boolean)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<System.Object, System.Boolean>();

        // Baracuda.Monitoring.Modules.FPSMonitor::TargetFrameRate (System.Int32)
        // Baracuda.Monitoring.Modules.FPSMonitor::Vsync (System.Int32)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<System.Object, System.Int32>();

        // Baracuda.Monitoring.Modules.ConsoleMonitor::Console (System.Collections.Generic.Queue<System.String>)
        // Baracuda.Monitoring.Modules.ConsoleMonitor::LastLogStacktrace (System.String)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<System.Object, System.Object>();

        // Player.PlayerController::DesiredSpeed (System.Single)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<System.Object, System.Single>();

        // PlayerControllerTcc::WallNormal (UnityEngine.Vector3)
        // PlayerControllerTcc::InvertWallNormal (UnityEngine.Vector3)
        // PlayerControllerTcc::MovementForceOnWallAxis (UnityEngine.Vector3)
        // Player.PlayerController::HorizontalVelocity (UnityEngine.Vector3)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<System.Object, UnityEngine.Vector3>();

        //  [Collection Definitions] 

        // System.Collections.Generic.Queue<System.String>
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefEnumerable<System.Object>();
    }
}

#endif //ENABLE_IL2CPP && !DISABLE_MONITORING

//----------------------------------------------------------------------------------------------------------------------

//--- Stats ---

//General

//Monitored Member:               42
//Monitored Member Instance:      42

//MemberInfo

//Monitored Fields:               31
//Monitored Fields Instance:      31
//Monitored Properties:           11
//Monitored Properties Instance:  11

//Monitored Types

//Monitored bool:                  5
//Monitored float:                 3
//Monitored int:                   4
//Monitored Queue<string>:         1
//Monitored string:               21
//Monitored Vector3:               8

//----------------------------------------------------------------------------------------------------------------------

//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring