name: Test
on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        id: latest_release
        uses: actions/github-script@v5
        with:
          script: |
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const latestRelease = releases.data[0];
            return latestRelease.id;

      - name: Print latest release ID
        run: echo "The latest release ID is ${{ steps.latest_release.outputs.result }}"